name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:
  pytest:
    runs-on: ${{ matrix.os }}-latest
    env:
      PYTEST_ADDOPTS: '--showlocals -vv --durations=10'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        py:
          - 3.9
          - 3.8
          - 3.7
#          - pypy3

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Update pip
        run: python -m pip install -U pip

      - name: Install dependencies
        run: python -m pip install toml packaging rich wheel pytest pytest-cov pytest-mock backports.cached-property pep621

      - name: Run tests
        run: python -m pytest --cov

      - uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: ${{ matrix.python }}
        with:
          flags: tests
          env_vars: PYTHON
          name: ${{ matrix.py }} - ${{ matrix.os }}

  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update pip
        run: python -m pip install -U pip

      - name: Install dependencies
        run: python -m pip install toml packaging rich wheel pytest pytest-cov pytest-mock backports.cached-property pep621 types-toml

      - name: Install mypy
        run: python -m pip install mypy

      - name: Run check for type
        run: python -m mypy -p trampolim
