name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:
  pytest:
    runs-on: ${{ matrix.os }}-latest
    env:
      PYTEST_ADDOPTS: '--showlocals -vv --durations=10'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        py:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
#          - pypy3

    steps:
      - uses: actions/checkout@v2

      - uses: excitedleigh/setup-nox@v2.0.0

      - name: Run tests
        run: nox --force-color -s test-${{ matrix.py }}

      - uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: ${{ matrix.py }}
        with:
          flags: tests
          env_vars: PYTHON
          name: ${{ matrix.py }} - ${{ matrix.os }}

  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run check for type
        run: pipx run nox -s type
